### ISSUE TITLE
Remove console.log from code

### ISSUE THREAD

**Issue by Infern1** [nodef/extra-fs#1]
I tested out your module for a good working `which` and indeed it works as expected on windows.

However was seeing strange message coming by in node output:
`ans.length`

Just found this is coming from https://github.com/nodef/extra-fs/blob/master/index.js#L126

WHy?

**Comment by wolfram77** [comment]
@Infern1 I must have put in a `main()` to test the walkDfs. I will remove that and make a commit.

I expect to improve this module, and was having a question regarding Node's `<fn>Sync()` functions. Do you still find these useful, after the introduction of async-await?

**Comment by Infern1** [comment]
> I expect to improve this module, and was having a question regarding Node's `<fn>Sync()` functions. Do you still find these useful, after the introduction of async-await?

I just can't comment on it... sorry not an expert on that

**Comment by wolfram77** [comment]
Sure. Thanks for creating the first comment.
